#FROM quay.io/ubi8/ubi-minimal:8.2
FROM  registry.access.redhat.com/ubi8/ubi-minimal:8.2

LABEL name="openshift-sandboxed-containers-operator-daemon" \
version="2.0.0" \
com.redhat.component="kata-data-container" \
summary="openshift-sandboxed-containers-operator manages the Openshift Sandboxed Containers runtime" \
maintainer="pradikum@redhat.com" \
io.k8s.display-name="openshift-sandboxed-containers-operator-daemon"

WORKDIR /
ADD daemon /
